---
title: "Introducció a R/Rstudio"
output: html_document
---

# Objectiu

L'objectiu del curs és introduir a l'alumne al llenguatge R a través de la plataforma de treball Rstudio. L'alumne serà capaç de:

  * conèixer les funcionalitats del programa,
  * estructurar els seus projectes en diferents espais de treball, 
  * importar dades d'Excel, CSV, SAS, SPSS i Stata,
  * introduir eines d'importació d'informació online: html, xml o json,
  * organitzar les taules de treball per extreure informació,
  * generar resultats de forma numèrica i gràfica utilitzant eines descriptives avançades i
  * presentar els seus resultats a través d'informes (pdf, html o word).


# Requisits

Coneixements d'estadística bàsica.


# Temari

  * Rstudio:
    * Estructura del programa. Configuració i personalització.
    * Rstudio com a plataforma de treball amb R. Principals funcionalitats.
    * Treball amb projectes.

  * R i Importació de fitxers:
    * Principals estructures de dades d'R (`vector`, `list`, `array` i `data.frame`).
    * Importació de la informació a R: des de Excel, SPSS, SAS, Stata, xml, json i html a R.

  * Treballar amb les teves dades:
    * Organitzar les teves dades (`tidyr`).
    * Descriure les teves dades (`dplyr`).
    * Visualitzar les teves dades (`ggplot2`).    
    * Presentar les teves dades : creació d'informes amb html, pdf i word (`knitr`).


