---
title: "Temporalització"
author: "Marc Comas and Iván Galván"
output: html_document
---


Curs de 15hores, separat en tres setmanes de la següent forma,

### 1r dia: Dilluns/dimarts (3h) [Marc]:

 * Presentació de nosaltres, presentar el curs/objectius bla bla bla (30min)
 * Rstudio com a plataforma de treball amb R. (30 min)
 * Principals funcionalitats:
    * Treballar amb projectes (15 min)
    * `Rmarkdown` i `knitr` (15 min)

Descans (15 min)

 * Introducció a R (1h30min):
    * Estructures d'R: vectors, matrius, llistes (data.frames) i funcions
    * Gràfics
    * Paquets
    
### 2n dia: Dimecres/Dijous (3h) [Handy Candy]:

  * Importació de dades a R (1h 30min)
    * Text/CSV
    * Excel
    * SPSS, Stata
    * html

Descans (15 min)

  * Estadística descritiva amb R (1h 30min)
    * Descriptiva numèrica i gràfica. (`summary`, `table`, `plot`, `boxplot`, `hist`)
    * Iteració a R (`apply`, `lapply`, `sapply`, `tapply`)
    
  
### 3r dia: Dilluns/dimarts (3h) [Marc]:

  * `dplyr` (1h)
  * `tidyr` (30min)
  
Descans (15 min)
  
  * Activitats `dplyr` i `tidyr` (1h 30min)
  
### 4t dia: Dimecres/Dijous (3h) [Handy Candy again]:

  * `ggplot2` (1h 30min)
  
Descans (15 min)
  
  * Activitats `ggplot2` (1h 30min)
  
### 5è dia: Dilluns/dimarts (3h) [Both]:

  * LLiure
  
